server:
  port: 8085
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    root: info
    de.unileipzig.dbs.pprl: info

spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: pprlpm
      username: pmadmin
      password: pmadminpw
      host: pprl-services-mongo
      port: 27017

management:
  jmx:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,mappings"
springdoc:
  show-actuator: true

pprl:
  services:
    data-owner-endpoint: "http://pprl-do:8081"
    linkage-unit-endpoint: "http://pprl-lu:8082"
    data-generator-endpoint: "http://pprl-dg:8086"