server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    root: info
    de.unileipzig.dbs.pprl: debug
    org.springframework.boot.autoconfigure.mongo.embedded: warn

spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: pprldo
      username: doadmin
      password: doadminpw
      host: pprl-services-mongo
      port: 27017

management:
  jmx:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,mappings"
springdoc:
  show-actuator: true

pprl:
  encodings:
    paths:
      - "/opt/pprl-services/do/configs"
  ks:
    location: "/opt/pprl-services/do/pprl-data-owner.jks"
    password: "secret-ks-password"

#dataset:
#  csv:
#    datasetConfigs:
#      -
#        location: "/opt/pprl-services/do/data/DS_Time.csv"
#        datasetId: -1
#        source: "org"
#      -
#        location: "/opt/pprl-services/do/data/DS_Time.csv"
#        datasetId: -2
#        source: "dup"
#    replace-existing: true