package de.unileipzig.dbs.pprl.service.dataowner.data.dto;

import de.unileipzig.dbs.pprl.service.dataowner.generator.DataSetGeneratorConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DatasetCorruptionRequestDto {

  @NotNull
  @Schema(description = "ID of the dataset used for the original records of the corrupted dataset",
          requiredMode = Schema.RequiredMode.REQUIRED)
  private Long inputDatasetId;

  @Schema(description = "ID of the generated dataset. If missing, it will be autogenerated.")
  private Long outputDatasetId;

  @Schema(description = "Configuration for the corrupter. Either config or configCreator must be set.")
  private DataSetGeneratorConfig config;

  @Schema(description = "Configuration for creating a corruption config from a template." +
          " Either config or configCreator must be set.")
  private DatasetGenerationConfigCreatorDto configCreator;

  @AssertTrue(message = "Exactly one of config or configCreator must be set")
  private boolean isConfigXorConfigCreator() {
    return (config == null) ^ (configCreator == null);
  }
}
