server:
  port: 8082
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    root: info
    de.unileipzig.dbs.pprl: info
    org.springframework.boot.autoconfigure.mongo.embedded: warn
    de.unileipzig.dbs.pprl.core.matcher.evaluation: warn

spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: pprllu
      username: luadmin
      password: luadminpw
      host: pprl-services-mongo
      port: 27017

management:
  jmx:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,mappings"
springdoc:
  show-actuator: true

pprl:
  services:
    classifier:
      endpoint: "http://pprl-classifier-service:8087"
      bearer-token: "secret"
  matchers:
    paths:
      - "/opt/pprl-services/lu/configs"
  reporting:
    includeAdditionalResultsByDefault: true
  lu:
    reporting:
      skip-blocking-reports: true