package de.unileipzig.dbs.pprl.service.dataowner.services;

import de.unileipzig.dbs.pprl.core.common.frequencies.AttributesFrequencyLookup;
import de.unileipzig.dbs.pprl.core.common.model.api.DataSet;
import de.unileipzig.dbs.pprl.core.common.model.api.Record;
import de.unileipzig.dbs.pprl.core.common.model.api.RecordId;
import de.unileipzig.dbs.pprl.core.common.monitoring.Tag;
import de.unileipzig.dbs.pprl.service.common.data.converter.RecordConverter;
import de.unileipzig.dbs.pprl.service.common.data.dto.DatasetDto;
import de.unileipzig.dbs.pprl.service.common.data.dto.RecordDto;
import de.unileipzig.dbs.pprl.service.common.dataset.MongoAttributesFrequencyLookupProvider;
import de.unileipzig.dbs.pprl.service.common.persistence.repositories.mongo.MongoFrequencyLookupRepository;
import de.unileipzig.dbs.pprl.service.common.services.AnalysisService;
import de.unileipzig.dbs.pprl.service.common.services.DatasetDtoService;
import de.unileipzig.dbs.pprl.service.common.services.DatasetIdService;
import de.unileipzig.dbs.pprl.service.common.services.DatasetMongoService;
import de.unileipzig.dbs.pprl.service.dataowner.data.dto.DatasetCorruptionRequestDto;
import de.unileipzig.dbs.pprl.service.dataowner.data.dto.DatasetGenerationConfigCreatorDto;
import de.unileipzig.dbs.pprl.service.dataowner.generator.DataSetGeneratorConfig;
import de.unileipzig.dbs.pprl.service.dataowner.generator.DataSetGeneratorConfigProvider;
import de.unileipzig.dbs.pprl.service.dataowner.generator.FilteredModifiedDataSetGenerator;
import de.unileipzig.dbs.pprl.service.dataowner.modifier.DataSetModifierConfig;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

import static de.unileipzig.dbs.pprl.service.common.utils.ConfigUtils.mergeNonNullProperties;

/**
 * Service for managing Data Owner PPRL services
 */
@Service
@Slf4j
public class CorrupterService {

  private static final RecordConverter converter = new RecordConverter();

  private final DatasetDtoService datasetDtoService;

  private final DatasetIdService datasetIdService;

  private final AnalysisService analysisService;

  private final MongoAttributesFrequencyLookupProvider frequencyLookupProvider;

  public CorrupterService(DatasetDtoService datasetDtoService, DatasetIdService datasetIdService, AnalysisService analysisService,
                          MongoFrequencyLookupRepository mongoFrequencyLookupRepository,
                          DatasetMongoService datasetMongoService) {
    this.datasetDtoService = datasetDtoService;
    this.datasetIdService = datasetIdService;
    this.analysisService = analysisService;
    this.frequencyLookupProvider = new MongoAttributesFrequencyLookupProvider(
            mongoFrequencyLookupRepository, datasetMongoService);
  }

  public DataSetGeneratorConfig getConfig(DatasetGenerationConfigCreatorDto configCreatorDto) {
    AttributesFrequencyLookup afl = frequencyLookupProvider.provide(configCreatorDto.getReferenceDatasetId());
    DataSetGeneratorConfig overrideConfig = configCreatorDto.getOverride();
    DataSetGeneratorConfigProvider provider = (overrideConfig != null && overrideConfig.getSeed() != null)
            ? new DataSetGeneratorConfigProvider(afl, overrideConfig.getSeed())
            : new DataSetGeneratorConfigProvider(afl);
    DataSetGeneratorConfig config = provider.getByName(configCreatorDto.getName());
    if (overrideConfig != null) {
      List<DataSetModifierConfig> sourceModifierConfigs = overrideConfig.getSourceModifierConfigs();
      if (sourceModifierConfigs != null && sourceModifierConfigs.isEmpty()) {
        overrideConfig.setSourceModifierConfigs(null);
      }
      List<DataSetModifierConfig> duplicateModifierConfigs = overrideConfig.getDuplicateModifierConfigs();
      if (duplicateModifierConfigs != null && duplicateModifierConfigs.isEmpty()) {
        overrideConfig.setDuplicateModifierConfigs(null);
      }
      mergeNonNullProperties(overrideConfig, config);
    }
    return config;
  }

  public Set<String> getConfigNames() {
    return new DataSetGeneratorConfigProvider().getAllConfigNames();
  }

  public long corruptDataset(DatasetCorruptionRequestDto requestDto) {
    DataSetGeneratorConfig config = requestDto.getConfig();
    if (config == null) {
      long referenceDatasetId = requestDto.getConfigCreator().getReferenceDatasetId();
      if (referenceDatasetId == 0) {
        log.info("No reference dataset found for request, using the input ({})", requestDto.getInputDatasetId());
        requestDto.getConfigCreator().setReferenceDatasetId(requestDto.getInputDatasetId());
      }
      config = getConfig(requestDto.getConfigCreator());
    }
    boolean autoGeneratedId = false;
    if (requestDto.getOutputDatasetId() == null) {
      requestDto.setOutputDatasetId(datasetIdService.generateDatasetId());
      autoGeneratedId = true;
    }
    return corruptDataset(requestDto.getInputDatasetId(), requestDto.getOutputDatasetId(), config, autoGeneratedId);
  }

  public long corruptDataset(long inputDatasetId,
                             long outputDatasetId,
                             DataSetGeneratorConfig config,
                             boolean autoGeneratedId) {
    FilteredModifiedDataSetGenerator generator = new FilteredModifiedDataSetGenerator(config);

    DatasetDto inputDataset = datasetDtoService.getDataset(inputDatasetId).orElseThrow(
            () -> new NoSuchElementException("Input dataset does not exist: " + inputDatasetId));

    List<RecordDto> originalRecordDtos = datasetDtoService.getAllRecordsAsDto(inputDatasetId);
    List<Record> records = originalRecordDtos.stream()
            .map(converter::toRecord)
            .toList();
    log.info("Generating based on dataset {} with {} records", inputDatasetId, records.size());
    DataSet output = generator.generate(records);
    Collection<Record> outputRecords = output.getAllRecords();
    // Get UniqueIds / Original Ids before inserting because this overrides them with the mongo uid
    Map<String, String> originalToModifiedIdMapping = outputRecords.stream()
            .map(Record::getId)
            .filter(id -> id.getOptionalId("ORIGINAL_ID").isPresent())
            .collect(Collectors.toMap(id -> id.getId("ORIGINAL_ID"), RecordId::getUniqueLikeId));
    List<RecordDto> recordDtos = outputRecords.stream()
            .map(converter::fromRecord)
            .peek(record -> record.setDatasetId(outputDatasetId))
            .toList();
    log.info("Generated {} records for output dataset {}", recordDtos.size(), outputDatasetId);

    datasetDtoService.deleteDataset(outputDatasetId);
    analysisService.deleteAnalysisResults(outputDatasetId);
    analysisService.deleteTags(outputDatasetId);

    DatasetDto datasetDto = DatasetDto.builder()
            .datasetName(inputDataset.getDatasetName() + " " + config.getConfigName())
            .datasetId(outputDatasetId)
            .build();
    if (autoGeneratedId) {
      datasetDto.getProperties().put("auto-generated-id", "true");
    }
    datasetDtoService.addDataset(datasetDto);
    log.info("Inserting {} generated records to database", recordDtos.size());
    datasetDtoService.insertAll(recordDtos);
    Collection<Tag> tagList = output.getTagTable().get().getTagList().stream()
            .peek(t -> t.setOrigin(Tag.ORIGIN_DATA_CORRUPTER))
            .toList();
    log.info("Adding {} corrupter tags", tagList.size());
    analysisService.saveTags(outputDatasetId, tagList);

    tagList = analysisService.getTags(inputDatasetId, Tag.ORIGIN_DATA_GENERATOR);
    tagList = tagList.stream()
            .filter(t -> originalToModifiedIdMapping.containsKey(t.getId0()))
            .peek(t -> t.setId0(originalToModifiedIdMapping.get(t.getId0())))
            .toList();
    log.info("Adding {} generator tags", tagList.size());
    analysisService.saveTags(outputDatasetId, tagList);
    return outputDatasetId;
  }

}
