/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.PredictionResponse;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BatchPredictionResponse
 */
@JsonPropertyOrder({
  BatchPredictionResponse.JSON_PROPERTY_PREDICTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class BatchPredictionResponse {
  public static final String JSON_PROPERTY_PREDICTIONS = "predictions";
  @javax.annotation.Nonnull
  private List<PredictionResponse> predictions = new ArrayList<>();

  public BatchPredictionResponse() {
  }

  public BatchPredictionResponse predictions(@javax.annotation.Nonnull List<PredictionResponse> predictions) {
    
    this.predictions = predictions;
    return this;
  }

  public BatchPredictionResponse addPredictionsItem(PredictionResponse predictionsItem) {
    if (this.predictions == null) {
      this.predictions = new ArrayList<>();
    }
    this.predictions.add(predictionsItem);
    return this;
  }

  /**
   * Get predictions
   * @return predictions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PREDICTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PredictionResponse> getPredictions() {
    return predictions;
  }


  @JsonProperty(JSON_PROPERTY_PREDICTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPredictions(@javax.annotation.Nonnull List<PredictionResponse> predictions) {
    this.predictions = predictions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchPredictionResponse batchPredictionResponse = (BatchPredictionResponse) o;
    return Objects.equals(this.predictions, batchPredictionResponse.predictions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(predictions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchPredictionResponse {\n");
    sb.append("    predictions: ").append(toIndentedString(predictions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private BatchPredictionResponse instance;

    public Builder() {
      this(new BatchPredictionResponse());
    }

    protected Builder(BatchPredictionResponse instance) {
      this.instance = instance;
    }

    public BatchPredictionResponse.Builder predictions(List<PredictionResponse> predictions) {
      this.instance.predictions = predictions;
      return this;
    }


    /**
    * returns a built BatchPredictionResponse instance.
    *
    * The builder is not reusable.
    */
    public BatchPredictionResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static BatchPredictionResponse.Builder builder() {
    return new BatchPredictionResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public BatchPredictionResponse.Builder toBuilder() {
    return new BatchPredictionResponse.Builder()
      .predictions(getPredictions());
  }


}

