/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FeaturesInnerValue
 */
@JsonPropertyOrder({
})
@JsonTypeName("Features_inner_value")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class FeaturesInnerValue {
  public FeaturesInnerValue() {
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeaturesInnerValue {\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private FeaturesInnerValue instance;

    public Builder() {
      this(new FeaturesInnerValue());
    }

    protected Builder(FeaturesInnerValue instance) {
      this.instance = instance;
    }



    /**
    * returns a built FeaturesInnerValue instance.
    *
    * The builder is not reusable.
    */
    public FeaturesInnerValue build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static FeaturesInnerValue.Builder builder() {
    return new FeaturesInnerValue.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public FeaturesInnerValue.Builder toBuilder() {
    return new FeaturesInnerValue.Builder();
  }


}

