/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.FeaturesInnerValue;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.ModelMetadata;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FitTrainingFitPost200Response
 */
@JsonPropertyOrder({
  FitTrainingFitPost200Response.JSON_PROPERTY_MODEL_DESCRIPTION,
  FitTrainingFitPost200Response.JSON_PROPERTY_METADATA,
  FitTrainingFitPost200Response.JSON_PROPERTY_DETAIL
})
@JsonTypeName("fit_training_fit_post_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class FitTrainingFitPost200Response {
  public static final String JSON_PROPERTY_MODEL_DESCRIPTION = "model_description";
  @javax.annotation.Nonnull
  private ModelMetadata modelDescription;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, FeaturesInnerValue>> metadata = JsonNullable.<Map<String, FeaturesInnerValue>>undefined();

  public static final String JSON_PROPERTY_DETAIL = "detail";
  @javax.annotation.Nullable
  private String detail = "Not supported";

  public FitTrainingFitPost200Response() {
  }

  public FitTrainingFitPost200Response modelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    
    this.modelDescription = modelDescription;
    return this;
  }

  /**
   * Get modelDescription
   * @return modelDescription
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelMetadata getModelDescription() {
    return modelDescription;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    this.modelDescription = modelDescription;
  }

  public FitTrainingFitPost200Response metadata(@javax.annotation.Nullable Map<String, FeaturesInnerValue> metadata) {
    this.metadata = JsonNullable.<Map<String, FeaturesInnerValue>>of(metadata);
    
    return this;
  }

  public FitTrainingFitPost200Response putMetadataItem(String key, FeaturesInnerValue metadataItem) {
    if (this.metadata == null || !this.metadata.isPresent()) {
      this.metadata = JsonNullable.<Map<String, FeaturesInnerValue>>of(new HashMap<>());
    }
    try {
      this.metadata.get().put(key, metadataItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, FeaturesInnerValue> getMetadata() {
        return metadata.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, FeaturesInnerValue>> getMetadata_JsonNullable() {
    return metadata;
  }
  
  @JsonProperty(JSON_PROPERTY_METADATA)
  public void setMetadata_JsonNullable(JsonNullable<Map<String, FeaturesInnerValue>> metadata) {
    this.metadata = metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, FeaturesInnerValue> metadata) {
    this.metadata = JsonNullable.<Map<String, FeaturesInnerValue>>of(metadata);
  }

  public FitTrainingFitPost200Response detail(@javax.annotation.Nullable String detail) {
    
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetail() {
    return detail;
  }


  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetail(@javax.annotation.Nullable String detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FitTrainingFitPost200Response fitTrainingFitPost200Response = (FitTrainingFitPost200Response) o;
    return Objects.equals(this.modelDescription, fitTrainingFitPost200Response.modelDescription) &&
        equalsNullable(this.metadata, fitTrainingFitPost200Response.metadata) &&
        Objects.equals(this.detail, fitTrainingFitPost200Response.detail);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelDescription, hashCodeNullable(metadata), detail);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FitTrainingFitPost200Response {\n");
    sb.append("    modelDescription: ").append(toIndentedString(modelDescription)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private FitTrainingFitPost200Response instance;

    public Builder() {
      this(new FitTrainingFitPost200Response());
    }

    protected Builder(FitTrainingFitPost200Response instance) {
      this.instance = instance;
    }

    public FitTrainingFitPost200Response.Builder modelDescription(ModelMetadata modelDescription) {
      this.instance.modelDescription = modelDescription;
      return this;
    }
    public FitTrainingFitPost200Response.Builder metadata(Map<String, FeaturesInnerValue> metadata) {
      this.instance.metadata = JsonNullable.<Map<String, FeaturesInnerValue>>of(metadata);
      return this;
    }
    public FitTrainingFitPost200Response.Builder metadata(JsonNullable<Map<String, FeaturesInnerValue>> metadata) {
      this.instance.metadata = metadata;
      return this;
    }
    public FitTrainingFitPost200Response.Builder detail(String detail) {
      this.instance.detail = detail;
      return this;
    }


    /**
    * returns a built FitTrainingFitPost200Response instance.
    *
    * The builder is not reusable.
    */
    public FitTrainingFitPost200Response build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static FitTrainingFitPost200Response.Builder builder() {
    return new FitTrainingFitPost200Response.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public FitTrainingFitPost200Response.Builder toBuilder() {
    return new FitTrainingFitPost200Response.Builder()
      .modelDescription(getModelDescription())
      .metadata(getMetadata())
      .detail(getDetail());
  }


}

