/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModelMetadata
 */
@JsonPropertyOrder({
  ModelMetadata.JSON_PROPERTY_MODEL_NAME,
  ModelMetadata.JSON_PROPERTY_MODEL_VERSION,
  ModelMetadata.JSON_PROPERTY_LABELS,
  ModelMetadata.JSON_PROPERTY_DESCRIPTION,
  ModelMetadata.JSON_PROPERTY_PARAMETERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class ModelMetadata {
  public static final String JSON_PROPERTY_MODEL_NAME = "model_name";
  @javax.annotation.Nullable
  private String modelName = "";

  public static final String JSON_PROPERTY_MODEL_VERSION = "model_version";
  @javax.annotation.Nullable
  private JsonNullable<String> modelVersion = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @javax.annotation.Nullable
  private List<String> labels = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description = "";

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, String>> parameters = JsonNullable.<Map<String, String>>undefined();

  public ModelMetadata() {
  }

  public ModelMetadata modelName(@javax.annotation.Nullable String modelName) {
    
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModelName() {
    return modelName;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelName(@javax.annotation.Nullable String modelName) {
    this.modelName = modelName;
  }

  public ModelMetadata modelVersion(@javax.annotation.Nullable String modelVersion) {
    this.modelVersion = JsonNullable.<String>of(modelVersion);
    
    return this;
  }

  /**
   * Get modelVersion
   * @return modelVersion
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getModelVersion() {
        return modelVersion.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getModelVersion_JsonNullable() {
    return modelVersion;
  }
  
  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  public void setModelVersion_JsonNullable(JsonNullable<String> modelVersion) {
    this.modelVersion = modelVersion;
  }

  public void setModelVersion(@javax.annotation.Nullable String modelVersion) {
    this.modelVersion = JsonNullable.<String>of(modelVersion);
  }

  public ModelMetadata labels(@javax.annotation.Nullable List<String> labels) {
    
    this.labels = labels;
    return this;
  }

  public ModelMetadata addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(@javax.annotation.Nullable List<String> labels) {
    this.labels = labels;
  }

  public ModelMetadata description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public ModelMetadata parameters(@javax.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
    
    return this;
  }

  public ModelMetadata putParametersItem(String key, String parametersItem) {
    if (this.parameters == null || !this.parameters.isPresent()) {
      this.parameters = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.parameters.get().put(key, parametersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getParameters() {
        return parameters.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getParameters_JsonNullable() {
    return parameters;
  }
  
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  public void setParameters_JsonNullable(JsonNullable<Map<String, String>> parameters) {
    this.parameters = parameters;
  }

  public void setParameters(@javax.annotation.Nullable Map<String, String> parameters) {
    this.parameters = JsonNullable.<Map<String, String>>of(parameters);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelMetadata modelMetadata = (ModelMetadata) o;
    return Objects.equals(this.modelName, modelMetadata.modelName) &&
        equalsNullable(this.modelVersion, modelMetadata.modelVersion) &&
        Objects.equals(this.labels, modelMetadata.labels) &&
        Objects.equals(this.description, modelMetadata.description) &&
        equalsNullable(this.parameters, modelMetadata.parameters);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelName, hashCodeNullable(modelVersion), labels, description, hashCodeNullable(parameters));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelMetadata {\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ModelMetadata instance;

    public Builder() {
      this(new ModelMetadata());
    }

    protected Builder(ModelMetadata instance) {
      this.instance = instance;
    }

    public ModelMetadata.Builder modelName(String modelName) {
      this.instance.modelName = modelName;
      return this;
    }
    public ModelMetadata.Builder modelVersion(String modelVersion) {
      this.instance.modelVersion = JsonNullable.<String>of(modelVersion);
      return this;
    }
    public ModelMetadata.Builder modelVersion(JsonNullable<String> modelVersion) {
      this.instance.modelVersion = modelVersion;
      return this;
    }
    public ModelMetadata.Builder labels(List<String> labels) {
      this.instance.labels = labels;
      return this;
    }
    public ModelMetadata.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public ModelMetadata.Builder parameters(Map<String, String> parameters) {
      this.instance.parameters = JsonNullable.<Map<String, String>>of(parameters);
      return this;
    }
    public ModelMetadata.Builder parameters(JsonNullable<Map<String, String>> parameters) {
      this.instance.parameters = parameters;
      return this;
    }


    /**
    * returns a built ModelMetadata instance.
    *
    * The builder is not reusable.
    */
    public ModelMetadata build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ModelMetadata.Builder builder() {
    return new ModelMetadata.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ModelMetadata.Builder toBuilder() {
    return new ModelMetadata.Builder()
      .modelName(getModelName())
      .modelVersion(getModelVersion())
      .labels(getLabels())
      .description(getDescription())
      .parameters(getParameters());
  }


}

