/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.BatchPredictionRequestFeaturesInnerValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PredictionRequest
 */
@JsonPropertyOrder({
  PredictionRequest.JSON_PROPERTY_MODEL_NAME,
  PredictionRequest.JSON_PROPERTY_MODEL_VERSION,
  PredictionRequest.JSON_PROPERTY_FEATURES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PredictionRequest {
  public static final String JSON_PROPERTY_MODEL_NAME = "model_name";
  @javax.annotation.Nonnull
  private String modelName;

  public static final String JSON_PROPERTY_MODEL_VERSION = "model_version";
  @javax.annotation.Nonnull
  private String modelVersion;

  public static final String JSON_PROPERTY_FEATURES = "features";
  @javax.annotation.Nonnull
  private Map<String, BatchPredictionRequestFeaturesInnerValue> features = new HashMap<>();

  public PredictionRequest() {
  }

  public PredictionRequest modelName(@javax.annotation.Nonnull String modelName) {
    
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModelName() {
    return modelName;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
  }

  public PredictionRequest modelVersion(@javax.annotation.Nonnull String modelVersion) {
    
    this.modelVersion = modelVersion;
    return this;
  }

  /**
   * Get modelVersion
   * @return modelVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModelVersion() {
    return modelVersion;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelVersion(@javax.annotation.Nonnull String modelVersion) {
    this.modelVersion = modelVersion;
  }

  public PredictionRequest features(@javax.annotation.Nonnull Map<String, BatchPredictionRequestFeaturesInnerValue> features) {
    
    this.features = features;
    return this;
  }

  public PredictionRequest putFeaturesItem(String key, BatchPredictionRequestFeaturesInnerValue featuresItem) {
    this.features.put(key, featuresItem);
    return this;
  }

  /**
   * Get features
   * @return features
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, BatchPredictionRequestFeaturesInnerValue> getFeatures() {
    return features;
  }


  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeatures(@javax.annotation.Nonnull Map<String, BatchPredictionRequestFeaturesInnerValue> features) {
    this.features = features;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionRequest predictionRequest = (PredictionRequest) o;
    return Objects.equals(this.modelName, predictionRequest.modelName) &&
        Objects.equals(this.modelVersion, predictionRequest.modelVersion) &&
        Objects.equals(this.features, predictionRequest.features);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelName, modelVersion, features);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionRequest {\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private PredictionRequest instance;

    public Builder() {
      this(new PredictionRequest());
    }

    protected Builder(PredictionRequest instance) {
      this.instance = instance;
    }

    public PredictionRequest.Builder modelName(String modelName) {
      this.instance.modelName = modelName;
      return this;
    }
    public PredictionRequest.Builder modelVersion(String modelVersion) {
      this.instance.modelVersion = modelVersion;
      return this;
    }
    public PredictionRequest.Builder features(Map<String, BatchPredictionRequestFeaturesInnerValue> features) {
      this.instance.features = features;
      return this;
    }


    /**
    * returns a built PredictionRequest instance.
    *
    * The builder is not reusable.
    */
    public PredictionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PredictionRequest.Builder builder() {
    return new PredictionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PredictionRequest.Builder toBuilder() {
    return new PredictionRequest.Builder()
      .modelName(getModelName())
      .modelVersion(getModelVersion())
      .features(getFeatures());
  }


}

