/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PredictionResponse
 */
@JsonPropertyOrder({
  PredictionResponse.JSON_PROPERTY_PREDICTION,
  PredictionResponse.JSON_PROPERTY_CONFIDENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class PredictionResponse {
  public static final String JSON_PROPERTY_PREDICTION = "prediction";
  @javax.annotation.Nonnull
  private Integer prediction;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @javax.annotation.Nullable
  private JsonNullable<BigDecimal> confidence = JsonNullable.<BigDecimal>undefined();

  public PredictionResponse() {
  }

  public PredictionResponse prediction(@javax.annotation.Nonnull Integer prediction) {
    
    this.prediction = prediction;
    return this;
  }

  /**
   * Get prediction
   * @return prediction
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PREDICTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPrediction() {
    return prediction;
  }


  @JsonProperty(JSON_PROPERTY_PREDICTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrediction(@javax.annotation.Nonnull Integer prediction) {
    this.prediction = prediction;
  }

  public PredictionResponse confidence(@javax.annotation.Nullable BigDecimal confidence) {
    this.confidence = JsonNullable.<BigDecimal>of(confidence);
    
    return this;
  }

  /**
   * Get confidence
   * @return confidence
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public BigDecimal getConfidence() {
        return confidence.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getConfidence_JsonNullable() {
    return confidence;
  }
  
  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  public void setConfidence_JsonNullable(JsonNullable<BigDecimal> confidence) {
    this.confidence = confidence;
  }

  public void setConfidence(@javax.annotation.Nullable BigDecimal confidence) {
    this.confidence = JsonNullable.<BigDecimal>of(confidence);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionResponse predictionResponse = (PredictionResponse) o;
    return Objects.equals(this.prediction, predictionResponse.prediction) &&
        equalsNullable(this.confidence, predictionResponse.confidence);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(prediction, hashCodeNullable(confidence));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionResponse {\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private PredictionResponse instance;

    public Builder() {
      this(new PredictionResponse());
    }

    protected Builder(PredictionResponse instance) {
      this.instance = instance;
    }

    public PredictionResponse.Builder prediction(Integer prediction) {
      this.instance.prediction = prediction;
      return this;
    }
    public PredictionResponse.Builder confidence(BigDecimal confidence) {
      this.instance.confidence = JsonNullable.<BigDecimal>of(confidence);
      return this;
    }
    public PredictionResponse.Builder confidence(JsonNullable<BigDecimal> confidence) {
      this.instance.confidence = confidence;
      return this;
    }


    /**
    * returns a built PredictionResponse instance.
    *
    * The builder is not reusable.
    */
    public PredictionResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PredictionResponse.Builder builder() {
    return new PredictionResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PredictionResponse.Builder toBuilder() {
    return new PredictionResponse.Builder()
      .prediction(getPrediction())
      .confidence(getConfidence());
  }


}

