/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.BatchPredictionRequestFeaturesInnerValue;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.ModelMetadata;

import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResponseFitTrainingFitPost
 */
@JsonPropertyOrder({
  ResponseFitTrainingFitPost.JSON_PROPERTY_MODEL_DESCRIPTION,
  ResponseFitTrainingFitPost.JSON_PROPERTY_METADATA,
  ResponseFitTrainingFitPost.JSON_PROPERTY_DETAIL
})
@JsonTypeName("Response_Fit_Training_Fit_Post")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class ResponseFitTrainingFitPost {
  public static final String JSON_PROPERTY_MODEL_DESCRIPTION = "model_description";
  @javax.annotation.Nonnull
  private ModelMetadata modelDescription;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, BatchPredictionRequestFeaturesInnerValue> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_DETAIL = "detail";
  @javax.annotation.Nullable
  private String detail = "Not supported";

  public ResponseFitTrainingFitPost() {
  }

  public ResponseFitTrainingFitPost modelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    
    this.modelDescription = modelDescription;
    return this;
  }

  /**
   * Description of the trained model.
   * @return modelDescription
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelMetadata getModelDescription() {
    return modelDescription;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    this.modelDescription = modelDescription;
  }

  public ResponseFitTrainingFitPost metadata(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public ResponseFitTrainingFitPost putMetadataItem(String key, BatchPredictionRequestFeaturesInnerValue metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, BatchPredictionRequestFeaturesInnerValue> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
    this.metadata = metadata;
  }

  public ResponseFitTrainingFitPost detail(@javax.annotation.Nullable String detail) {
    
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetail() {
    return detail;
  }


  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetail(@javax.annotation.Nullable String detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseFitTrainingFitPost responseFitTrainingFitPost = (ResponseFitTrainingFitPost) o;
    return Objects.equals(this.modelDescription, responseFitTrainingFitPost.modelDescription) &&
        Objects.equals(this.metadata, responseFitTrainingFitPost.metadata) &&
        Objects.equals(this.detail, responseFitTrainingFitPost.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelDescription, metadata, detail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseFitTrainingFitPost {\n");
    sb.append("    modelDescription: ").append(toIndentedString(modelDescription)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseFitTrainingFitPost instance;

    public Builder() {
      this(new ResponseFitTrainingFitPost());
    }

    protected Builder(ResponseFitTrainingFitPost instance) {
      this.instance = instance;
    }

    public ResponseFitTrainingFitPost.Builder modelDescription(ModelMetadata modelDescription) {
      this.instance.modelDescription = modelDescription;
      return this;
    }
    public ResponseFitTrainingFitPost.Builder metadata(Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
      this.instance.metadata = metadata;
      return this;
    }
    public ResponseFitTrainingFitPost.Builder detail(String detail) {
      this.instance.detail = detail;
      return this;
    }


    /**
    * returns a built ResponseFitTrainingFitPost instance.
    *
    * The builder is not reusable.
    */
    public ResponseFitTrainingFitPost build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseFitTrainingFitPost.Builder builder() {
    return new ResponseFitTrainingFitPost.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseFitTrainingFitPost.Builder toBuilder() {
    return new ResponseFitTrainingFitPost.Builder()
      .modelDescription(getModelDescription())
      .metadata(getMetadata())
      .detail(getDetail());
  }


}

