/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.Sample;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.StrategyType;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Request for selecting which samples to send to labelers in an active learning process.
 */
@JsonPropertyOrder({
  SampleSelectionRequest.JSON_PROPERTY_STRATEGY_TYPE,
  SampleSelectionRequest.JSON_PROPERTY_STRATEGY_OPTIONS,
  SampleSelectionRequest.JSON_PROPERTY_SAMPLES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class SampleSelectionRequest {
  public static final String JSON_PROPERTY_STRATEGY_TYPE = "strategy_type";
  @javax.annotation.Nonnull
  private StrategyType strategyType;

  public static final String JSON_PROPERTY_STRATEGY_OPTIONS = "strategy_options";
  @javax.annotation.Nullable
  private Map<String, String> strategyOptions = new HashMap<>();

  public static final String JSON_PROPERTY_SAMPLES = "samples";
  @javax.annotation.Nonnull
  private List<Sample> samples = new ArrayList<>();

  public SampleSelectionRequest() {
  }

  public SampleSelectionRequest strategyType(@javax.annotation.Nonnull StrategyType strategyType) {
    
    this.strategyType = strategyType;
    return this;
  }

  /**
   * Which sampling strategy to use.
   * @return strategyType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STRATEGY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StrategyType getStrategyType() {
    return strategyType;
  }


  @JsonProperty(JSON_PROPERTY_STRATEGY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStrategyType(@javax.annotation.Nonnull StrategyType strategyType) {
    this.strategyType = strategyType;
  }

  public SampleSelectionRequest strategyOptions(@javax.annotation.Nullable Map<String, String> strategyOptions) {
    
    this.strategyOptions = strategyOptions;
    return this;
  }

  public SampleSelectionRequest putStrategyOptionsItem(String key, String strategyOptionsItem) {
    if (this.strategyOptions == null) {
      this.strategyOptions = new HashMap<>();
    }
    this.strategyOptions.put(key, strategyOptionsItem);
    return this;
  }

  /**
   * Parameters specific to the chosen strategy. E.g. {&#39;batch_size&#39;: 10, &#39;threshold&#39;: 0.8}.
   * @return strategyOptions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STRATEGY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getStrategyOptions() {
    return strategyOptions;
  }


  @JsonProperty(JSON_PROPERTY_STRATEGY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrategyOptions(@javax.annotation.Nullable Map<String, String> strategyOptions) {
    this.strategyOptions = strategyOptions;
  }

  public SampleSelectionRequest samples(@javax.annotation.Nonnull List<Sample> samples) {
    
    this.samples = samples;
    return this;
  }

  public SampleSelectionRequest addSamplesItem(Sample samplesItem) {
    if (this.samples == null) {
      this.samples = new ArrayList<>();
    }
    this.samples.add(samplesItem);
    return this;
  }

  /**
   * List of candidate samples to choose from.
   * @return samples
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Sample> getSamples() {
    return samples;
  }


  @JsonProperty(JSON_PROPERTY_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSamples(@javax.annotation.Nonnull List<Sample> samples) {
    this.samples = samples;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SampleSelectionRequest sampleSelectionRequest = (SampleSelectionRequest) o;
    return Objects.equals(this.strategyType, sampleSelectionRequest.strategyType) &&
        Objects.equals(this.strategyOptions, sampleSelectionRequest.strategyOptions) &&
        Objects.equals(this.samples, sampleSelectionRequest.samples);
  }

  @Override
  public int hashCode() {
    return Objects.hash(strategyType, strategyOptions, samples);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SampleSelectionRequest {\n");
    sb.append("    strategyType: ").append(toIndentedString(strategyType)).append("\n");
    sb.append("    strategyOptions: ").append(toIndentedString(strategyOptions)).append("\n");
    sb.append("    samples: ").append(toIndentedString(samples)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SampleSelectionRequest instance;

    public Builder() {
      this(new SampleSelectionRequest());
    }

    protected Builder(SampleSelectionRequest instance) {
      this.instance = instance;
    }

    public SampleSelectionRequest.Builder strategyType(StrategyType strategyType) {
      this.instance.strategyType = strategyType;
      return this;
    }
    public SampleSelectionRequest.Builder strategyOptions(Map<String, String> strategyOptions) {
      this.instance.strategyOptions = strategyOptions;
      return this;
    }
    public SampleSelectionRequest.Builder samples(List<Sample> samples) {
      this.instance.samples = samples;
      return this;
    }


    /**
    * returns a built SampleSelectionRequest instance.
    *
    * The builder is not reusable.
    */
    public SampleSelectionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SampleSelectionRequest.Builder builder() {
    return new SampleSelectionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SampleSelectionRequest.Builder toBuilder() {
    return new SampleSelectionRequest.Builder()
      .strategyType(getStrategyType())
      .strategyOptions(getStrategyOptions())
      .samples(getSamples());
  }


}

