/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Response listing which samples were selected.
 */
@JsonPropertyOrder({
  SampleSelectionResponse.JSON_PROPERTY_SELECTED_IDS,
  SampleSelectionResponse.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class SampleSelectionResponse {
  public static final String JSON_PROPERTY_SELECTED_IDS = "selected_ids";
  @javax.annotation.Nonnull
  private List<String> selectedIds = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, String>> metadata = JsonNullable.<Map<String, String>>undefined();

  public SampleSelectionResponse() {
  }

  public SampleSelectionResponse selectedIds(@javax.annotation.Nonnull List<String> selectedIds) {
    
    this.selectedIds = selectedIds;
    return this;
  }

  public SampleSelectionResponse addSelectedIdsItem(String selectedIdsItem) {
    if (this.selectedIds == null) {
      this.selectedIds = new ArrayList<>();
    }
    this.selectedIds.add(selectedIdsItem);
    return this;
  }

  /**
   * List of sample IDs chosen for labeling.
   * @return selectedIds
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SELECTED_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getSelectedIds() {
    return selectedIds;
  }


  @JsonProperty(JSON_PROPERTY_SELECTED_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelectedIds(@javax.annotation.Nonnull List<String> selectedIds) {
    this.selectedIds = selectedIds;
  }

  public SampleSelectionResponse metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = JsonNullable.<Map<String, String>>of(metadata);
    
    return this;
  }

  public SampleSelectionResponse putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null || !this.metadata.isPresent()) {
      this.metadata = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.metadata.get().put(key, metadataItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getMetadata() {
        return metadata.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getMetadata_JsonNullable() {
    return metadata;
  }
  
  @JsonProperty(JSON_PROPERTY_METADATA)
  public void setMetadata_JsonNullable(JsonNullable<Map<String, String>> metadata) {
    this.metadata = metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = JsonNullable.<Map<String, String>>of(metadata);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SampleSelectionResponse sampleSelectionResponse = (SampleSelectionResponse) o;
    return Objects.equals(this.selectedIds, sampleSelectionResponse.selectedIds) &&
        equalsNullable(this.metadata, sampleSelectionResponse.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectedIds, hashCodeNullable(metadata));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SampleSelectionResponse {\n");
    sb.append("    selectedIds: ").append(toIndentedString(selectedIds)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SampleSelectionResponse instance;

    public Builder() {
      this(new SampleSelectionResponse());
    }

    protected Builder(SampleSelectionResponse instance) {
      this.instance = instance;
    }

    public SampleSelectionResponse.Builder selectedIds(List<String> selectedIds) {
      this.instance.selectedIds = selectedIds;
      return this;
    }
    public SampleSelectionResponse.Builder metadata(Map<String, String> metadata) {
      this.instance.metadata = JsonNullable.<Map<String, String>>of(metadata);
      return this;
    }
    public SampleSelectionResponse.Builder metadata(JsonNullable<Map<String, String>> metadata) {
      this.instance.metadata = metadata;
      return this;
    }


    /**
    * returns a built SampleSelectionResponse instance.
    *
    * The builder is not reusable.
    */
    public SampleSelectionResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SampleSelectionResponse.Builder builder() {
    return new SampleSelectionResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SampleSelectionResponse.Builder toBuilder() {
    return new SampleSelectionResponse.Builder()
      .selectedIds(getSelectedIds())
      .metadata(getMetadata());
  }


}

