/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A single sample, optionally including a ground-truth label.
 */
@JsonPropertyOrder({
  Sample.JSON_PROPERTY_ID,
  Sample.JSON_PROPERTY_FEATURES,
  Sample.JSON_PROPERTY_LABEL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Sample {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private JsonNullable<String> id = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FEATURES = "features";
  @javax.annotation.Nonnull
  private Map<String, BigDecimal> features = new HashMap<>();

  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nullable
  private JsonNullable<Integer> label = JsonNullable.<Integer>undefined();

  public Sample() {
  }

  public Sample id(@javax.annotation.Nullable String id) {
    this.id = JsonNullable.<String>of(id);
    
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getId() {
        return id.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getId_JsonNullable() {
    return id;
  }
  
  @JsonProperty(JSON_PROPERTY_ID)
  public void setId_JsonNullable(JsonNullable<String> id) {
    this.id = id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = JsonNullable.<String>of(id);
  }

  public Sample features(@javax.annotation.Nonnull Map<String, BigDecimal> features) {
    
    this.features = features;
    return this;
  }

  public Sample putFeaturesItem(String key, BigDecimal featuresItem) {
    this.features.put(key, featuresItem);
    return this;
  }

  /**
   * Arbitrary feature data for the sample, e.g. {&#39;text&#39;: &#39;...&#39;, &#39;score&#39;: 0.42}.
   * @return features
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, BigDecimal> getFeatures() {
    return features;
  }


  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeatures(@javax.annotation.Nonnull Map<String, BigDecimal> features) {
    this.features = features;
  }

  public Sample label(@javax.annotation.Nullable Integer label) {
    this.label = JsonNullable.<Integer>of(label);
    
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getLabel() {
        return label.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLabel_JsonNullable() {
    return label;
  }
  
  @JsonProperty(JSON_PROPERTY_LABEL)
  public void setLabel_JsonNullable(JsonNullable<Integer> label) {
    this.label = label;
  }

  public void setLabel(@javax.annotation.Nullable Integer label) {
    this.label = JsonNullable.<Integer>of(label);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sample sample = (Sample) o;
    return equalsNullable(this.id, sample.id) &&
        Objects.equals(this.features, sample.features) &&
        equalsNullable(this.label, sample.label);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(id), features, hashCodeNullable(label));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sample {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private Sample instance;

    public Builder() {
      this(new Sample());
    }

    protected Builder(Sample instance) {
      this.instance = instance;
    }

    public Sample.Builder id(String id) {
      this.instance.id = JsonNullable.<String>of(id);
      return this;
    }
    public Sample.Builder id(JsonNullable<String> id) {
      this.instance.id = id;
      return this;
    }
    public Sample.Builder features(Map<String, BigDecimal> features) {
      this.instance.features = features;
      return this;
    }
    public Sample.Builder label(Integer label) {
      this.instance.label = JsonNullable.<Integer>of(label);
      return this;
    }
    public Sample.Builder label(JsonNullable<Integer> label) {
      this.instance.label = label;
      return this;
    }


    /**
    * returns a built Sample instance.
    *
    * The builder is not reusable.
    */
    public Sample build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Sample.Builder builder() {
    return new Sample.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Sample.Builder toBuilder() {
    return new Sample.Builder()
      .id(getId())
      .features(getFeatures())
      .label(getLabel());
  }


}

