/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.BatchPredictionRequestFeaturesInnerValue;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.ModelMetadata;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Response of a training job.
 */
@JsonPropertyOrder({
  TrainingResponse.JSON_PROPERTY_MODEL_DESCRIPTION,
  TrainingResponse.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class TrainingResponse {
  public static final String JSON_PROPERTY_MODEL_DESCRIPTION = "model_description";
  @javax.annotation.Nonnull
  private ModelMetadata modelDescription;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> metadata = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>undefined();

  public TrainingResponse() {
  }

  public TrainingResponse modelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    
    this.modelDescription = modelDescription;
    return this;
  }

  /**
   * Description of the trained model.
   * @return modelDescription
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelMetadata getModelDescription() {
    return modelDescription;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelDescription(@javax.annotation.Nonnull ModelMetadata modelDescription) {
    this.modelDescription = modelDescription;
  }

  public TrainingResponse metadata(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
    this.metadata = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(metadata);
    
    return this;
  }

  public TrainingResponse putMetadataItem(String key, BatchPredictionRequestFeaturesInnerValue metadataItem) {
    if (this.metadata == null || !this.metadata.isPresent()) {
      this.metadata = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(new HashMap<>());
    }
    try {
      this.metadata.get().put(key, metadataItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, BatchPredictionRequestFeaturesInnerValue> getMetadata() {
        return metadata.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> getMetadata_JsonNullable() {
    return metadata;
  }
  
  @JsonProperty(JSON_PROPERTY_METADATA)
  public void setMetadata_JsonNullable(JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> metadata) {
    this.metadata = metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
    this.metadata = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(metadata);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingResponse trainingResponse = (TrainingResponse) o;
    return Objects.equals(this.modelDescription, trainingResponse.modelDescription) &&
        equalsNullable(this.metadata, trainingResponse.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelDescription, hashCodeNullable(metadata));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingResponse {\n");
    sb.append("    modelDescription: ").append(toIndentedString(modelDescription)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private TrainingResponse instance;

    public Builder() {
      this(new TrainingResponse());
    }

    protected Builder(TrainingResponse instance) {
      this.instance = instance;
    }

    public TrainingResponse.Builder modelDescription(ModelMetadata modelDescription) {
      this.instance.modelDescription = modelDescription;
      return this;
    }
    public TrainingResponse.Builder metadata(Map<String, BatchPredictionRequestFeaturesInnerValue> metadata) {
      this.instance.metadata = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(metadata);
      return this;
    }
    public TrainingResponse.Builder metadata(JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> metadata) {
      this.instance.metadata = metadata;
      return this;
    }


    /**
    * returns a built TrainingResponse instance.
    *
    * The builder is not reusable.
    */
    public TrainingResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TrainingResponse.Builder builder() {
    return new TrainingResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TrainingResponse.Builder toBuilder() {
    return new TrainingResponse.Builder()
      .modelDescription(getModelDescription())
      .metadata(getMetadata());
  }


}

