/*
 * Classification API
 *  Services for - training, updating, and predicting using a classification model - selecting samples for active learning processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.BatchPredictionRequestFeaturesInnerValue;
import de.unileipzig.dbs.pprl.service.linkageunit.services.clients.classifier.model.Sample;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Request for running training job.  You must provide **either**:   1. &#x60;features&#x60; (a list of feature dicts) **and** &#x60;labels&#x60; (a parallel list of ints), **or**   2. &#x60;samples&#x60; (a list of &#x60;Sample&#x60; objects, each embedding its own features + label).  Omitting both combinations (or providing only one of &#x60;features&#x60;/&#x60;labels&#x60;) will be rejected.
 */
@JsonPropertyOrder({
  TrainingRequest.JSON_PROPERTY_MODEL_NAME,
  TrainingRequest.JSON_PROPERTY_MODEL_VERSION,
  TrainingRequest.JSON_PROPERTY_OUTPUT_MODEL_VERSION,
  TrainingRequest.JSON_PROPERTY_FEATURES,
  TrainingRequest.JSON_PROPERTY_LABELS,
  TrainingRequest.JSON_PROPERTY_SAMPLES,
  TrainingRequest.JSON_PROPERTY_OPTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class TrainingRequest {
  public static final String JSON_PROPERTY_MODEL_NAME = "model_name";
  @javax.annotation.Nonnull
  private String modelName;

  public static final String JSON_PROPERTY_MODEL_VERSION = "model_version";
  @javax.annotation.Nonnull
  private String modelVersion;

  public static final String JSON_PROPERTY_OUTPUT_MODEL_VERSION = "output_model_version";
  @javax.annotation.Nonnull
  private String outputModelVersion;

  public static final String JSON_PROPERTY_FEATURES = "features";
  @javax.annotation.Nullable
  private JsonNullable<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>> features = JsonNullable.<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>>undefined();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @javax.annotation.Nullable
  private JsonNullable<List<Integer>> labels = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_SAMPLES = "samples";
  @javax.annotation.Nullable
  private JsonNullable<List<Sample>> samples = JsonNullable.<List<Sample>>undefined();

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> options = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>undefined();

  public TrainingRequest() {
  }

  public TrainingRequest modelName(@javax.annotation.Nonnull String modelName) {
    
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModelName() {
    return modelName;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
  }

  public TrainingRequest modelVersion(@javax.annotation.Nonnull String modelVersion) {
    
    this.modelVersion = modelVersion;
    return this;
  }

  /**
   * Get modelVersion
   * @return modelVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModelVersion() {
    return modelVersion;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelVersion(@javax.annotation.Nonnull String modelVersion) {
    this.modelVersion = modelVersion;
  }

  public TrainingRequest outputModelVersion(@javax.annotation.Nonnull String outputModelVersion) {
    
    this.outputModelVersion = outputModelVersion;
    return this;
  }

  /**
   * Get outputModelVersion
   * @return outputModelVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OUTPUT_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOutputModelVersion() {
    return outputModelVersion;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputModelVersion(@javax.annotation.Nonnull String outputModelVersion) {
    this.outputModelVersion = outputModelVersion;
  }

  public TrainingRequest features(@javax.annotation.Nullable List<Map<String, BatchPredictionRequestFeaturesInnerValue>> features) {
    this.features = JsonNullable.<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>>of(features);
    
    return this;
  }

  public TrainingRequest addFeaturesItem(Map<String, BatchPredictionRequestFeaturesInnerValue> featuresItem) {
    if (this.features == null || !this.features.isPresent()) {
      this.features = JsonNullable.<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>>of(new ArrayList<>());
    }
    try {
      this.features.get().add(featuresItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get features
   * @return features
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<Map<String, BatchPredictionRequestFeaturesInnerValue>> getFeatures() {
        return features.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>> getFeatures_JsonNullable() {
    return features;
  }
  
  @JsonProperty(JSON_PROPERTY_FEATURES)
  public void setFeatures_JsonNullable(JsonNullable<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>> features) {
    this.features = features;
  }

  public void setFeatures(@javax.annotation.Nullable List<Map<String, BatchPredictionRequestFeaturesInnerValue>> features) {
    this.features = JsonNullable.<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>>of(features);
  }

  public TrainingRequest labels(@javax.annotation.Nullable List<Integer> labels) {
    this.labels = JsonNullable.<List<Integer>>of(labels);
    
    return this;
  }

  public TrainingRequest addLabelsItem(Integer labelsItem) {
    if (this.labels == null || !this.labels.isPresent()) {
      this.labels = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.labels.get().add(labelsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<Integer> getLabels() {
        return labels.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getLabels_JsonNullable() {
    return labels;
  }
  
  @JsonProperty(JSON_PROPERTY_LABELS)
  public void setLabels_JsonNullable(JsonNullable<List<Integer>> labels) {
    this.labels = labels;
  }

  public void setLabels(@javax.annotation.Nullable List<Integer> labels) {
    this.labels = JsonNullable.<List<Integer>>of(labels);
  }

  public TrainingRequest samples(@javax.annotation.Nullable List<Sample> samples) {
    this.samples = JsonNullable.<List<Sample>>of(samples);
    
    return this;
  }

  public TrainingRequest addSamplesItem(Sample samplesItem) {
    if (this.samples == null || !this.samples.isPresent()) {
      this.samples = JsonNullable.<List<Sample>>of(new ArrayList<>());
    }
    try {
      this.samples.get().add(samplesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get samples
   * @return samples
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<Sample> getSamples() {
        return samples.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Sample>> getSamples_JsonNullable() {
    return samples;
  }
  
  @JsonProperty(JSON_PROPERTY_SAMPLES)
  public void setSamples_JsonNullable(JsonNullable<List<Sample>> samples) {
    this.samples = samples;
  }

  public void setSamples(@javax.annotation.Nullable List<Sample> samples) {
    this.samples = JsonNullable.<List<Sample>>of(samples);
  }

  public TrainingRequest options(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> options) {
    this.options = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(options);
    
    return this;
  }

  public TrainingRequest putOptionsItem(String key, BatchPredictionRequestFeaturesInnerValue optionsItem) {
    if (this.options == null || !this.options.isPresent()) {
      this.options = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(new HashMap<>());
    }
    try {
      this.options.get().put(key, optionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, BatchPredictionRequestFeaturesInnerValue> getOptions() {
        return options.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> getOptions_JsonNullable() {
    return options;
  }
  
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  public void setOptions_JsonNullable(JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> options) {
    this.options = options;
  }

  public void setOptions(@javax.annotation.Nullable Map<String, BatchPredictionRequestFeaturesInnerValue> options) {
    this.options = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(options);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingRequest trainingRequest = (TrainingRequest) o;
    return Objects.equals(this.modelName, trainingRequest.modelName) &&
        Objects.equals(this.modelVersion, trainingRequest.modelVersion) &&
        Objects.equals(this.outputModelVersion, trainingRequest.outputModelVersion) &&
        equalsNullable(this.features, trainingRequest.features) &&
        equalsNullable(this.labels, trainingRequest.labels) &&
        equalsNullable(this.samples, trainingRequest.samples) &&
        equalsNullable(this.options, trainingRequest.options);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelName, modelVersion, outputModelVersion, hashCodeNullable(features), hashCodeNullable(labels), hashCodeNullable(samples), hashCodeNullable(options));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingRequest {\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    outputModelVersion: ").append(toIndentedString(outputModelVersion)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    samples: ").append(toIndentedString(samples)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private TrainingRequest instance;

    public Builder() {
      this(new TrainingRequest());
    }

    protected Builder(TrainingRequest instance) {
      this.instance = instance;
    }

    public TrainingRequest.Builder modelName(String modelName) {
      this.instance.modelName = modelName;
      return this;
    }
    public TrainingRequest.Builder modelVersion(String modelVersion) {
      this.instance.modelVersion = modelVersion;
      return this;
    }
    public TrainingRequest.Builder outputModelVersion(String outputModelVersion) {
      this.instance.outputModelVersion = outputModelVersion;
      return this;
    }
    public TrainingRequest.Builder features(List<Map<String, BatchPredictionRequestFeaturesInnerValue>> features) {
      this.instance.features = JsonNullable.<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>>of(features);
      return this;
    }
    public TrainingRequest.Builder features(JsonNullable<List<Map<String, BatchPredictionRequestFeaturesInnerValue>>> features) {
      this.instance.features = features;
      return this;
    }
    public TrainingRequest.Builder labels(List<Integer> labels) {
      this.instance.labels = JsonNullable.<List<Integer>>of(labels);
      return this;
    }
    public TrainingRequest.Builder labels(JsonNullable<List<Integer>> labels) {
      this.instance.labels = labels;
      return this;
    }
    public TrainingRequest.Builder samples(List<Sample> samples) {
      this.instance.samples = JsonNullable.<List<Sample>>of(samples);
      return this;
    }
    public TrainingRequest.Builder samples(JsonNullable<List<Sample>> samples) {
      this.instance.samples = samples;
      return this;
    }
    public TrainingRequest.Builder options(Map<String, BatchPredictionRequestFeaturesInnerValue> options) {
      this.instance.options = JsonNullable.<Map<String, BatchPredictionRequestFeaturesInnerValue>>of(options);
      return this;
    }
    public TrainingRequest.Builder options(JsonNullable<Map<String, BatchPredictionRequestFeaturesInnerValue>> options) {
      this.instance.options = options;
      return this;
    }


    /**
    * returns a built TrainingRequest instance.
    *
    * The builder is not reusable.
    */
    public TrainingRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TrainingRequest.Builder builder() {
    return new TrainingRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TrainingRequest.Builder toBuilder() {
    return new TrainingRequest.Builder()
      .modelName(getModelName())
      .modelVersion(getModelVersion())
      .outputModelVersion(getOutputModelVersion())
      .features(getFeatures())
      .labels(getLabels())
      .samples(getSamples())
      .options(getOptions());
  }


}

